### ISSUE TITLE
data_utils/process.py中path被写死了。

### ISSUE THREAD

**Issue by charles4song** [notiom/ER-nerf#4]
# 问题1：
```
 opt = parser.parse_args()
 opt.path = '/home/yanxiaole/Aigc/ER-NeRF/data/rad-nerf/obama/obama.mp4'
```

问题2：
[INFO] ===== extract background image from /home/ER-NeRF/data/obama/ori_imgs =====
Traceback (most recent call last):
  File "/home/ER-nerf/data_utils/process.py", line 389, in <module>
    extract_background(base_dir, ori_imgs_dir)
  File "/home/ER-nerf/data_utils/process.py", line 76, in extract_background
    tmp_image = cv2.imread(image_paths[0], cv2.IMREAD_UNCHANGED) # [H, W, 3]
IndexError: list index out of range

**Comment by charles4song** [comment]
问题2解决办法：
下载ori_imgs.zip放到data/obama/ori_imgs路径下即可。但是正常不应该是process.py生成么？  @notiom

**Comment by charles4song** [comment]
> 问题2解决办法： 下载ori_imgs.zip放到data/obama/ori_imgs路径下即可。但是正常不应该是process.py生成么？ @notiom

我的错误。已经安装了ffmpeg但是再次运行容器还是提示未安装，重新安装即可。
